// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseU5fSs6jvtTAQbo0dWrfjYix2G35wsg',
    appId: '1:349432700609:web:794dfc135762a905bbbe40',
    messagingSenderId: '349432700609',
    projectId: 'keep-7ffef',
    authDomain: 'keep-7ffef.firebaseapp.com',
    databaseURL: 'https://keep-7ffef-default-rtdb.firebaseio.com',
    storageBucket: 'keep-7ffef.firebasestorage.app',
    measurementId: 'G-LZZTE0D00F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaHFzUNNA1UPe04dPY3pZmzqaB7B1gEA',
    appId: '1:349432700609:android:0cb145b36b61d163bbbe40',
    messagingSenderId: '349432700609',
    projectId: 'keep-7ffef',
    databaseURL: 'https://keep-7ffef-default-rtdb.firebaseio.com',
    storageBucket: 'keep-7ffef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWYy4UtQjjbV7eM6Ch6AVyLfbFvQBAXY',
    appId: '1:349432700609:ios:321944a72727938cbbbe40',
    messagingSenderId: '349432700609',
    projectId: 'keep-7ffef',
    databaseURL: 'https://keep-7ffef-default-rtdb.firebaseio.com',
    storageBucket: 'keep-7ffef.firebasestorage.app',
    androidClientId: '349432700609-87varnbe9g5kipi93dch7ip5a1lcp1ub.apps.googleusercontent.com',
    iosClientId: '349432700609-uku2n9dechbtqrduirji2sncl0ev40mn.apps.googleusercontent.com',
    iosBundleId: 'net.nexoviasolutions.keep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWYy4UtQjjbV7eM6Ch6AVyLfbFvQBAXY',
    appId: '1:349432700609:ios:321944a72727938cbbbe40',
    messagingSenderId: '349432700609',
    projectId: 'keep-7ffef',
    databaseURL: 'https://keep-7ffef-default-rtdb.firebaseio.com',
    storageBucket: 'keep-7ffef.firebasestorage.app',
    androidClientId: '349432700609-87varnbe9g5kipi93dch7ip5a1lcp1ub.apps.googleusercontent.com',
    iosClientId: '349432700609-uku2n9dechbtqrduirji2sncl0ev40mn.apps.googleusercontent.com',
    iosBundleId: 'net.nexoviasolutions.keep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCseU5fSs6jvtTAQbo0dWrfjYix2G35wsg',
    appId: '1:349432700609:web:2bc269be5e899e78bbbe40',
    messagingSenderId: '349432700609',
    projectId: 'keep-7ffef',
    authDomain: 'keep-7ffef.firebaseapp.com',
    databaseURL: 'https://keep-7ffef-default-rtdb.firebaseio.com',
    storageBucket: 'keep-7ffef.firebasestorage.app',
    measurementId: 'G-H18JWKZ0W4',
  );

}